### ISSUE TITLE
Function not outputting the same hash as built-in function

### ISSUE THREAD

**Issue by jjmontgo** [ircmaxell/password_compat#112]
The function doesn't output the same hash as PHP 7.2.

PHP 5.3.10 using this function
`$hash = password_hash('mypassword', PASSWORD_BCRYPT, array('cost' => 10));`
$hash is $2y$10$mdrfl9XUF9J/qe2wnxopNevC1HtAcVxmYz9JSoetyABJggR7aMmNe

PHP 7.2.24 calling native password_hash()
`$hash = password_hash('mypassword', PASSWORD_BCRYPT, array('cost' => 10));`
$hash is $2y$10$HV3YTr/Mg2KvijZzUz9VDet.dlLbeKqToYHhodFCnCURgZVz.VEy2

Am I missing something?

**Comment by ircmaxell** [comment]
That is by design. It should always output a different hash. [Here's an explanation](https://stackoverflow.com/a/50412764/338665).

**Comment by jjmontgo** [comment]
Yeah, don't mind me.  I wasn't supplying it with the same salt.

**Comment by ircmaxell** [comment]
One note: the salt parameter has been removed as of PHP-8, so my suggestion would be to not use it: https://github.com/php/php-src/commit/94ae35c9fbc34b26c514b2ba097e021744100f28

**Comment by jjmontgo** [comment]
Oh, ok thanks.  

If I didn't use my own salt, and I later upgraded to a version of PHP where password_hash() is built in, how would I verify the stored hashes if a different hash is output?

**Comment by miquelfire** [comment]
password_verify()

**Comment by ircmaxell** [comment]
^^ That exactly. The hash value is supposed to change on every single call to password-hash. Instead, you use password_verify to check if an existing hash matches a password.

**Comment by jjmontgo** [comment]
I've never used this function and am used to storing a hash, random salt
and hash algo in the database.

I tested password_hash() followed by password_verify() between this
function and the built-in function and it continues to work great.

Thanks!

**Comment by ircmaxell** [comment]
Suggestion: do not implement a salt yourself. There is no need to store the hash algo in the DB as well. The output of password_hash has everything required to re-create it, including a random salt, an algo identifier, and the options. It manages it all for you, and that's the design of it.
