### ISSUE TITLE
Question: What should happen when an incompatible hash is passed to password_verify?

### ISSUE THREAD

**Issue by Lekensteyn** [ircmaxell/password_compat#23]
The documentation says that the hash of `password_hash` should be passed as `hash` parameter to `password_verify`. It does not say anything about the result when this value contains something else.

I store the result of `password_hash` in a database and check it against a password later on (as documented). But if the password is not initialized, an empty value is passed to `password_verify`. The verification fails as `crypt()` makes up its own salt, but that was for this particular case.

Are there any guarantees on the validation result when the hash is not exactly a return value of `password_hash`? (note that the password argument can be anything as this is passed by the user)

**Comment by weirdan** [comment]
FYI native password_verify() does *not* reject DES hashes: https://3v4l.org/hKl4X

**Comment by GrahamCampbell** [comment]
It DOES ignore them though on 7.0+.

**Comment by weirdan** [comment]
3v4l snippet posted above shows opposite. Do you think they use patched php build that specifically enables this behavior?

**Comment by GrahamCampbell** [comment]
Don't know. I might be wrong though. ;)

**Comment by weirdan** [comment]
7.0.1 and 7.0.0 accept them:
```
❯ vendor/bin/phpunit test/Unit/PasswordVerifyTest.php --testdox                                                                                        password_compat/git/accept_des_hashes 
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.1 with Xdebug 2.4.0RC4-dev
Configuration:	/home/weirdan/src/password_compat/phpunit.xml.dist
Warning:	Deprecated configuration setting "strict" used

PasswordVerify
 [...snip...]
 [x] Des hashes are accepted
```
```
❯ vendor/bin/phpunit test/Unit/PasswordVerifyTest.php --testdox                                                                                        password_compat/git/accept_des_hashes 
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.0 with Xdebug 2.4.0RC4-dev
Configuration:	/home/weirdan/src/password_compat/phpunit.xml.dist
Warning:	Deprecated configuration setting "strict" used

PasswordVerify
 [...snip...]
 [x] Des hashes are accepted
```

**Comment by GrahamCampbell** [comment]
I'm wrong then. ;)
