### ISSUE TITLE
script timeout on password_verify

### ISSUE THREAD

**Issue by pine3ree** [ircmaxell/password_compat#78]
Hello,

i accidentally happened to check hashed with password_verify() some strings starting with:
$2y$27$
$2y$31$

The function call takes long time to run starting from string beginning $2y$16$ - $2y$17$ up to $2y$31$. with $2y$27$ the script timeout is reached.

(it also happens for string just identical to the previous ones)

the same calls using php5.5 password_verify quickly return false. 

kind regards

PS
my php ver 5.3.29

**Comment by ircmaxell** [comment]
can you provide a test hash (and associated password) to reproduce this?

**Comment by pine3ree** [comment]
```php
$result = password_verify('secret', '$2y$27$');
```
in PHP 5.3.29 custom build in Ubuntu 12.04 (xdebug disabled via php.ini)

'./configure' '--prefix=/srv/php/53' '--sysconfdir=/srv/etc/php/53' '--with-config-file-path=/srv/etc/php/53' '--with-config-file-scan-dir=/srv/etc/php/53/conf.d' '--with-mysql=shared,/usr' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--with-mysqli=shared,/usr/bin/mysql_config' '--with-sqlite=shared' '--enable-sqlite-utf8' '--enable-pdo' '--with-pdo-mysql=shared,/usr' '--with-pdo-sqlite=shared,/usr' '--with-zlib=shared' '--with-zlib-dir=/usr' '--with-bz2=shared,/usr' '--enable-zip=shared,/usr' '--with-gmp=shared,/usr' '--with-gd=shared' '--enable-gd-native-ttf' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--with-xpm-dir=/usr' '--with-freetype-dir=/usr' '--enable-exif' '--with-curl=shared,/usr' '--with-mhash=shared,/usr' '--with-mcrypt=shared,/usr' '--with-imap=/usr' '--with-imap-ssl=/usr' '--with-kerberos=/usr' '--with-gettext=shared,/usr' '--with-xsl=shared,/usr' '--with-openssl=/usr' '--enable-ftp=shared' '--enable-json=shared' '--enable-libxml=shared' '--with-libxml-dir=/usr' '--enable-xmlreader=shared' '--enable-xmlwriter=shared' '--enable-dom=shared' '--with-xsl=shared,/usr' '--enable-ctype=shared' '--enable-session=shared' '--with-tidy=shared,/usr' '--with-iconv=shared' '--with-iconv-dir=/usr' '--with-pcre-dir=/usr' '--with-ldap=shared,/usr' '--with-ldap-sasl=/usr' '--enable-mbstring=shared' '--enable-bcmath=shared' '--enable-intl=shared' '--enable-soap=shared' '--enable-cli' '--enable-cgi' '--with-libdir=/lib/x86_64-linux-gnu'

i'll get back in a few minutes with the same test in php 5.4

**Comment by pine3ree** [comment]
Hello Anthony, i can confirm the same results with php 5.4.37

**Comment by ircmaxell** [comment]
The problem is that prior to PHP 5.5, `$2y$10$` was a valid salt. That was because crypt internally padded the salt with `$` characters. This was in error, as it's not actually a valid salt.

If you run 5.5+ with that salt, you'll get `*0` which tells you there was an internal error. 5.5 and above will fail to validate any hash with invalid salts (less than 22 characters). 5.4 and earlier will still try to validate them.
