### ISSUE TITLE
which version to download?

### ISSUE THREAD

**Issue by nimasdj** [ircmaxell/password_compat#85]
@ircmaxell For latest 'stable' version for product environment, should I download 'dev-master' or v1.0.4 as of today?

**Comment by lode** [comment]
Fyi, the only functional difference in master is from https://github.com/ircmaxell/password_compat/pull/79.

**Comment by GrahamCampbell** [comment]
I'd say always go for a stable tag.

**Comment by nimasdj** [comment]
I left my comment under #79 to keep consistency between dev-master and stable tag.

**Comment by ircmaxell** [comment]
Master and stable are by definition not consistent. One is stable, and one is not.

I intentionally did not push a new release after merging #79. It would be fine to now (and I likely will), but there's a reason for the delay. I will explain in #79. 

You should **always** use a production tag when you are using the code in production. Never use dev-master in production. It's as simple as that.
