### ISSUE TITLE
E_USER_ERROR vs warning

### ISSUE THREAD

**Issue by nimasdj** [ircmaxell/password_compat#86]
If it makes sense, I suggest to consider to use E_USER_ERROR for the followings 2 lines instead of warning.
https://github.com/ircmaxell/password_compat/blob/master/lib/password.php#L37
https://github.com/ircmaxell/password_compat/blob/master/lib/password.php#L235
I submitted PR #87

**Comment by ircmaxell** [comment]
That was done deliberately to maintain compatibility with PHP 5.5+
