### ISSUE TITLE
function_exists('PasswordCompat\\binary\\_strlen') needed?

### ISSUE THREAD

**Issue by DanielRuf** [ircmaxell/password_compat#89]
I don't know why this check is there, but the namespace and so the function name (full qualified name) are unique and thus this it is not necessary in my opinion (and normally a namespace is just defined once), or am I wrong?

https://github.com/ircmaxell/password_compat/blob/1ecb013b51756effed3a3c446a314084b54c9916/lib/password.php#L256
https://github.com/ircmaxell/password_compat/blob/1ecb013b51756effed3a3c446a314084b54c9916/lib/password.php#L316

**Comment by lode** [comment]
I would say it is done to help people using `require()` instead of `require_once()`. It is done for all normal functions as well: https://github.com/ircmaxell/password_compat/blob/1ecb013b51756effed3a3c446a314084b54c9916/lib/password.php#L24.

**Comment by DanielRuf** [comment]
Ok, this would explain it and makes sense. Thanks for the hint.

Although I would just require once (we can at least check if the function exists). But it seems the library itself does not define a namespace to keep it simple so the functions are in the global namespace and can be directly used, is this correct?

So this was done to keep it as simple as possible so users can directly include / require and use the functions for passwor dhashing?

I think we can close this ticket, did not think about people who require the functions more than once.

**Comment by lode** [comment]
The functions are in global namespace as they are meant as a fallback for the native functions (http://php.net/password_hash) which are only available since php 5.5. Once you are working with php 5.5+ you should not need this library anymore.

**Comment by DanielRuf** [comment]
Right. Oversaw this fact (I am only including and using the file for configurations where PHP > 5.3.7 and < 5.5.0 runs).
