### ISSUE TITLE
Problem with verifiying the hashed password

### ISSUE THREAD

**Issue by trekmp** [ircmaxell/password_compat#95]
Doesn't work on PHP **5.6.98**, but does on **5.4.25**.

Have ran the test script and came back with Pass.  Have checked using **password_get_info** and both servers return the same information, so at a loss as why this doesn't work. It's not the code as I know it's working because it does on the 5.4.25 server.

Any suggestions, really need to get this working?

**Comment by GrahamCampbell** [comment]
> 5.6.98

Is there a typo there?

**Comment by trekmp** [comment]
Not as far as I can tell, that is what is returned from phpinfo();
![clipboard02](https://cloud.githubusercontent.com/assets/18479243/17924697/95c21726-69e1-11e6-99b6-ad1eb1badae6.jpg)

**Comment by ircmaxell** [comment]
You're using an unofficial build. There is no "5.6.98" version of PHP. That means what you're using must be a fork.

Can you share the code you're using that works on 5.4, but not on 5.6?
