### ISSUE TITLE
Using the project on a newer version of PHP

### ISSUE THREAD

**Issue by assaflei** [ircmaxell/password_compat#96]
Hi,
My site is currently installed on a server with PHP 5.4.16 and I want to start hashing passwords on a site there.
In the future I will migrate to a server with later version of PHP and will be able to use the standard password_hash methods

Will the verification of older values work on the newer version? Or should I stay with this solution in later versions of PHP as well?

What is the recommended practice?

Thanks!

**Comment by staabm** [comment]
This library is a polyfill for the password api which is built into php natively since 5.5. so you either use the native stuff on 5.5+ or you use this lib with php 5.3.7+.

**Comment by ircmaxell** [comment]
Yes, it will work, it was designed for that explicit use-case.
