### ISSUE TITLE
use password_compact in codeigniter

### ISSUE THREAD

**Issue by asadghazanfary** [ircmaxell/password_compat#98]
hello everyone

i have a question:

how can use password_compact in **codeigniter version 3**?

please help me

thank you

**Comment by jeffstoner** [comment]
Copy password.php into your helpers directory, rename it to password_helper.php, then just load the helper in your controller/library/model like any other.

`$this->load->helper('password_helper');

$hash = password_hash($password, PASSWORD_DEFAULT, array('cost' => $this->cost));

// Update the user's password in the 'users' table
$this->db->set('password_hash', $hash);
$this->db->where('username', $username);
$this->db->update('users');

$this->db->reset_query();

// get the stored password hash
$query = $this->db->select('password_hash')->where('username', $username)->get('users');
$result = $query->row();

// check to see if the password given to us matches what we stored
if (password_verify($password, $result->password_hash)) {
   // Passwords match
   return TRUE;
} else {
   // Password mismatch
   return FALSE;
}
`

**Comment by asadghazanfary** [comment]
thank you so much @jeffstoner 
You've done a great help to me

**Comment by asadghazanfary** [comment]
> 

> [

- [ ] @1. #92 

](url)
