### ISSUE TITLE
This lib on php 5.5

### ISSUE THREAD

**Issue by nimasdj** [ircmaxell/password_compat#99]
Don't we need to this library on php 5.5? Or is there any cases that we may still need this library on php 5.5?
@ircmaxell

**Comment by GrahamCampbell** [comment]
No, you don't need this library.

**Comment by nimasdj** [comment]
I am using randomlib to generated random string and number but in composer I see it requires this password_compat that I don't use it. Why randomlib requires this lib?

**Comment by GrahamCampbell** [comment]
It only requires it to cater for PHP 5.4 etc. Installing this library on php 5.5+ is not going to break anything, but it will not get used.

An ideal way would be to use a virtual package for the password functions, and have php 5.5+ and password_compat "provide" it, but, we don't have this, so. :/

**Comment by nimasdj** [comment]
Please give example what or how to have in virtual package as you said? Please clarify.

**Comment by GrahamCampbell** [comment]
> Please give example what or how to have in virtual package as you said? Please clarify.

It was just a remark about the package ecosystem. Nothing you can do about it in this case, because no such virtual package exists.

**Comment by nimasdj** [comment]
Thanks.
